### ISSUE TITLE
Geany: black/white toolbar

### ISSUE THREAD

**Issue by hlechner** [solus-cold-storage/evopop-gtk-theme#49]
There is a interesting geany's feature to put toolbar aside of menu. however make it inconsistent with non-light theme.

Look this screenshot:
![image](https://cloud.githubusercontent.com/assets/11244067/7668616/714dfbd6-fc18-11e4-8b25-ee1729d574aa.png)

The Geany at the present version uses GTK+ (GTK 3 version is in development).

I've tried a little to change only Geany's toolbar to dark-style but without success. Only what I found close is the "Main" Geany Widget:

``` widget "Geany*" style "geany-test" ```

Thanks!

**Comment by hlechner** [comment]
It seems that there is no specific widget to define the toolbar background color.

The only widget that I could use to change the toolbar background is:
``` widget "GeanyMainWindow" style "testing" ```
![image](https://cloud.githubusercontent.com/assets/11244067/7687437/c08e73e0-fd73-11e4-8a6c-a98aad3b20bf.png)

Other possible solution is to use the "light-menubar" for this application specific (Geany)

There is a widget called ``GeanyToolbar`` however it doesn't change the background color.

**Comment by poltertec** [comment]
thx for the info i'll have a look at it asap
