### ISSUE TITLE
Please add support to gnome 3.18

### ISSUE THREAD

**Issue by fdinardo** [solus-cold-storage/evopop-gtk-theme#58]
Hi, 
I really appreciated your design. 
Unfortunately the gtk theme doesn't work properly with the new gnome 3.18.
I'm available to help in this porting, but i'm not expert enough with gtk theming, so if you have suggestions I'm here...!

Thanks for your amazing work!

**Comment by bcclsn** [comment]
up!

**Comment by manrajsingh** [comment]
up!

**Comment by ikeydoherty** [comment]
There is no maintainer for this project that's why its in the cold storage account

**Comment by bcclsn** [comment]
:(

**Comment by fdinardo** [comment]
@ikeydoherty ok, thanks for the explanation. 

I'm going to fork this project but first, i would know what you think about this, then if you agree, please can you provide me some documentations or examples of GTK3 themeing. Unfortunately Gnome has poor docs about this argument, or i wasn't able to find something helpful!
Thanks in advance

**Comment by hobbypunk90** [comment]
@fdinardo sounds great :+1: i hope this help?
http://worldofgnome.org/making-gtk3-themes-part-1-basics/

**Comment by ikeydoherty** [comment]
So I'd be over the moon if someone forks this! This is why we left it publicly accessible, so that the work was never lost :) Please, feel free, after all this is FOSS ^^

**Comment by fdinardo** [comment]
@hobbypunk90 I read that post few time ago. The problem is that every update version of gtk they add others elements in the UI and i don't know how to select them via CSS. However i will try to keep this repo alive, but due the lack of free time i don't know when it will be ready.

@ikeydoherty

**Comment by bcclsn** [comment]
@fdinardo il tema ARC e anche quello Numix sono stati aggiornati a gnome 3.18 e non hanno il bug su Nautilus. ho dato uno sguardo ai sorgenti  e ho visto che i file sono strutturati in maniera diversa, però forse può esserti utile :)
io purtroppo non sono molto esperto di css...

**Comment by fdinardo** [comment]
@bcclsn Grazie, stavo proprio cercando un tema aggiornato che non replicasse il problema. 
Purtroppo il modo di organizzare i files non è sempre lo stesso. Adoro il modo in cui hanno organizzato i file in questo repo, e dato che il tema "proviene" dal numix è probabile che abbiano la stessa organizzazione. Spero di poter aggioranare al più presto!

**Comment by bcclsn** [comment]
@fdinardo se hai bisogno di una mano, contattami e farò il possibile :) questo tema merita di sopravvivere!!!

**Comment by fdinardo** [comment]
@bcclsn Sicuramente!
Anzi visto che ti trovi nel mio fork sono gia riuscito a visualizzare la riga selezionata in nautilus nella sidebar. Tu potresti aiutarmi con il test. Clona il repo e se risolvi qualche issue ancora meglio :smile:

**Comment by bcclsn** [comment]
@fdinardo purtroppo non so risolverle :(

**Comment by bcclsn** [comment]
per il test, invece, con molto piacere *_*

**Comment by fdinardo** [comment]
@bcclsn Ciao, dopo un po di tempo ho cercato di migliorare l'aspetto in gnome 3.18. Potresti dargli uno sguardo e vedere cosa ne pensi.
Usa il mio fork non questo altrimenti non vedrai i cambiamenti

Grazie

**Comment by bcclsn** [comment]
@fdinardo grande!!!! il tema funziona e nautilus no sballa più la configurazione della sidebar.
restano da fixare giusto un paio di cose nella sidebar:
1. le voci Recenti Home Cestino etc. sono leggermente decentrate (se comparate a tutti gli altri temi)
2. la barra di selezione (blu evopop) delle voci Recenti Home Cestino etc. è decentrata, ovvero inizia dal bordo sinistro della finestra, ma termina qualche pixel prima

altro:
3. la progress bar introdotta con gnome 3.18 resta nera e sul tema scuro si vede appena. andrebbe colorata di bianco, come per le altre icone della barra del titolo

**Comment by fdinardo** [comment]
Ti ringrazio per il feedback. 
Se ti è possibile, potresti aggiungere delle immagini in modo da farmi capire meglio.
Per il momento le modifiche sono relative solo alla versione Dark del tema. Per le modifiche su quella ligth, basta semplicemente copiare e incollare perché i colori vengono definiti in gtk.css, cosa che farò alla fine invece di fare il lavoro due volte.

**Comment by bcclsn** [comment]
1. http://s16.postimg.org/s2cahd2mt/Schermata_da_2015_09_11_14_12_45.png
2. http://s16.postimg.org/5ex1b7n2t/Schermata_da_2015_10_22_09_28_48.png
3. http://s27.postimg.org/5zxc3bcmr/Schermata_da_2015_10_25_15_40_50.png
4. http://s15.postimg.org/h4d29p11n/Schermata_da_2015_10_25_15_53_27.png

se noti, nella foto 1 e 2, le voci Rcenti, Home, Cestino, etc. della sidebar sono più centrate, rispetto all'immagine 3. inoltre, sempre dal confronto 1vs3, puoi notare che la barra "blu" che evidenzia la voce Home (sempre nella sidebar) ha i bordi arrotondati e non ad angolo retto.
per intenderci, 1. è il tema su gnome 3.16 e 2. è il tuo fork su gnome 3.18

passando, poi, ad un confronto 3vs4, puoi notare il bug della progress bar introdotta in nautilus con la 3.18
nei due screen puoi vedere il tuo fork (3.) paragonato al tema Flat-Plat (4.). nella barra del titolo, sulla destra, accanto alla lente di ingrandimento (tasto "cerca"), l'icona del "progresso di copia" è nera su barra nera nel tuo fork e nera su barra bianca nello screen 4. se su flat-plat (4.) seleziono il tema dark, l'icona diventa bianca su barra nera... cosa che non accade nel tuo fork (3.)

spero di essermi spiegato bene... purtroppo su gtk3-widget-factory non riuscivo a capire quali elementi guardare. 

premesso, poi, che possiamo usare canali privati quali mail o g+, ti informo che ho contattato il mantainer del pacchetto evopop-gtk3-theme-git su AUR (uso archlinux) per segnalargli il tuo fork e l'aggiornamento del pacchetto. il mantainer non risponde e, autorizzato da un moderatore del forum arch, ho/hai il permesso per pubblicare un nuovo pacchetto su aur, relativo al tuo fork e, quindi, aggiornato. fammi sapere se sei interessato, posso darti una mano con il pkgbuild :)

**Comment by fdinardo** [comment]
Ti ringrazio per la spiegazione. 
Credo sia più appropriato usare canali privati per la collaborazione e aprire un nuovo issue in inglese sul mio fork. 
Anche io uso archlinux e aggiornare il pacchetto sarebbe una cosa stupenda.
Dal momento che esiste già il pacchetto, aspettiamo una risposta dal mantainer. In caso di mancata risposta prolungata, creiamo un nuovo pacchetto in AUR.

**Comment by bcclsn** [comment]
ti aggiungo su g+ e continuiamo in pvt :)

**Comment by Abhinav1217** [comment]
@fdinardo I cloned your repo https://github.com/fdinardo/evopop-gtk-theme but I am getting this error
```
[Abhinav@localhost Evopop] $ sudo sh autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal  --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
autogen.sh: line 2: ./configure: No such file or directory
[Abhinav@localhost Evopop] $ 
```

What am I doing wrong.

**Comment by fdinardo** [comment]
@Abhinav1217 Try to not do 'sudo' but only `sh autogen.sh` in one of your `$HOME` direcetory. 
If it works try:
`sudo make install`
to install the theme in /usr/share/themes

Let me know if it works.

Bye

**Comment by Abhinav1217** [comment]
Tried that too.. Didn't work. First tried without  sudo. Then tried with sudo thinking maybe it was some permission issue. Same message as above.

**Comment by fdinardo** [comment]
@Abhinav1217 please can you show the ls output of the dir Evopop?

**Comment by Abhinav1217** [comment]
Current content is 
```
[Abhinav@localhost Evopop] $ ll
total 64
-rwxrwxr-x. 1 Abhinav Abhinav    44 Nov  6 19:17 autogen.sh
-rwxrwxr-x. 1 Abhinav Abhinav   495 Nov  6 19:17 configure.ac
-rwxrwxr-x. 1 Abhinav Abhinav   346 Nov  6 19:17 CREDITS
drwxrwxr-x. 4 Abhinav Abhinav  4096 Nov  6 19:17 evopop-gtk-theme
drwxrwxr-x. 4 Abhinav Abhinav  4096 Nov  6 19:17 evopop-light-gtk-theme
-rwxrwxr-x. 1 Abhinav Abhinav 35122 Nov  6 19:17 LICENSE
-rwxrwxr-x. 1 Abhinav Abhinav   543 Nov  6 19:17 Makefile.am
-rwxrwxr-x. 1 Abhinav Abhinav  1129 Nov  6 19:17 README.md
```

I did `git clone <your-repo> Evopop && cd Evopop`. Then I did `sh autogen.sh` Got the same error given before, I thought it was some issue with permission, so I did `sudo sh autogen.sh` Same error.

**Comment by Abhinav1217** [comment]
Current content is 
```
[Abhinav@localhost Evopop] $ ll
total 64
-rwxrwxr-x. 1 Abhinav Abhinav    44 Nov  6 19:17 autogen.sh
-rwxrwxr-x. 1 Abhinav Abhinav   495 Nov  6 19:17 configure.ac
-rwxrwxr-x. 1 Abhinav Abhinav   346 Nov  6 19:17 CREDITS
drwxrwxr-x. 4 Abhinav Abhinav  4096 Nov  6 19:17 evopop-gtk-theme
drwxrwxr-x. 4 Abhinav Abhinav  4096 Nov  6 19:17 evopop-light-gtk-theme
-rwxrwxr-x. 1 Abhinav Abhinav 35122 Nov  6 19:17 LICENSE
-rwxrwxr-x. 1 Abhinav Abhinav   543 Nov  6 19:17 Makefile.am
-rwxrwxr-x. 1 Abhinav Abhinav  1129 Nov  6 19:17 README.md
```

I did `git clone <your-repo> Evopop && cd Evopop`. Then I did `sh autogen.sh` Got the same error given before, I thought it was some issue with permission, so I did `sudo sh autogen.sh` Same error.

**Comment by fdinardo** [comment]
The problem is that you don't have `automake` installed in your system.
Install it and retry.
Let me know.

**Comment by Abhinav1217** [comment]
I have it installed.  
```
[Abhinav@localhost ~] $ rpm --query automake
automake-1.15-4.fc23.noarch
[Abhinav@localhost ~] $ 
```

**Comment by bcclsn** [comment]
@Abhinav1217: try to download only evopop-gtk-theme folder and put it in /usr/share/themes or ~/.themes... without to compile using the script

**Comment by fdinardo** [comment]
@Abhinav1217 install it again, and make sure you have installed this packages:
* autoconf
* automake
* m4

A workaround could be the hint provided by @bcclsn.
```
# cp -r evopop-gtk-theme /usr/share/theme
```
for all the user.
```
$ cp -r evopo-gtk-theme ~/.themes
```
for the current user only.

---
I have closed this issue because we are not talking anymore about the porting, that is partially done, at 3.18
I'm interesting to resolve this issue to figure out which dependencies we need to include in the AUR package. Thanks

**Comment by Tigro** [comment]
Guys, use this build for F23: http://koji.russianfedora.pro/koji/buildinfo?buildID=1894

**Comment by Abhinav1217** [comment]
@Tigro Thanks. It is quite fixed. Only thing missing is the new file progress bar in Nautilus, Which is still not that visible. But sidebar and all the stuffs are now all set.

**Comment by fdinardo** [comment]
@Tigro The scripts in that package are the same of this one. Why that package could be different from this? No customization found for fedora.

@Abhinav1217 this is really weird because they changed only the css (like i did) to fit for 3.18... Are you sure that my repo doesn't work for you?

**Comment by Tigro** [comment]
@fdinardo Please, show me screenshot with new progress bar, so I can compare with current theme.

**Comment by okanakalin** [comment]
Unfortunately, the theme is still not working very well for Geary. The folder list and the email list have some serious problems: misaligned boxes and borders, labels disappearing/changing colors when they shouldn't, labels at the top and bottom of the list covered by a gray box. 

The last problem seems to be stemming from the rubber band effect lists have when you try to scroll them beyond the border.

Still good work! I hope you can completely port it to 3.18 since EvoPop is one of the few really good themes out there.

**Comment by fdinardo** [comment]
@Tigro i'm not referring to the css changes i meant that the script in the link provided by you are the same of these scripts. Why that package works for fedora and this one not?
What do you mean with "new progress bar"? 
Are you mean the new operations_actions in Nautilus?
The new operations_actions is an icon. For example when you copy a file from a drive to another, It appears in the header bar, but the circle is an animated icon. You cannot change color of this button because it is a normal button and all the changes will affect all the buttons. I tried to change the background color just to make it more visible in a dark panel, but the ID "operations_button" doesn't work. 

@okanakalin Thanks for the feddback. 
What is your Geary Version? 0.6 or 0.10?

**Comment by Abhinav1217** [comment]
Yes I meant operation action in nautilus. I didn't knew what it was called.  It is almost invisible if screen brightness is even a bit low.

**Comment by okanakalin** [comment]
I am using the stock version that comes with Fedora 23 (0.10.0).

**Comment by fdinardo** [comment]
@okanakalin Please can you download latest version of my branch and let me see if there is an improvement?

I just fixed the overshoot issue (a shady border on over scroll).

**Comment by fdinardo** [comment]
@Tigro Finally fixed the new progress bar issue with the last commit!

**Comment by okanakalin** [comment]
That problem is certainly fixed. However, I noticed a couple of other problems. I feel like I should open an issue about that instead of hijacking this thread but here it goes: 

Selected email in the list has turquoise background color. However, the box of that colored rectangle does not match the border of the labels in the list. It is shifted downward for some reason.

If you open an email with images in it, Geary puts two labels on top of the email for enabling/disabling images from that sender. Those labels are completely white when the mouse is not over them.

The resizable separator (divider?) between the IMAP folder list and email list should have three dots on it but in my system, I see a small white dots with random gray pixels around them. It looks it cannot render the proper image there.  

I don't know if this is related to the theme but also I have a hidpi screen and the icons in the email list (star icon and the read/unread icon) and the icons in the message view pane are low resolution and blurry.

Another thing which might be related to the design of Geary is the scrollbar in email list. It is rendered on the date labels, occluding them and it looks weird since scrollbar is rendered only partially.

Geary is still quite usable though and I didn't notice anything in other applications.

**Comment by fdinardo** [comment]
@okanakalin you're right. It's better to open a separate issue. 

I knew all of these problems, but since i have reached a good state of improvement for Geary, i thought to commit it and get it usable. 

I'm still working on these problems.
Thanks for the feedback.
