### ISSUE TITLE
My prio's for next release

### ISSUE THREAD

**Issue by poltertec** [solus-cold-storage/evopop-gtk-theme#61]
**Add Gtk 3.20 support**
- [x]  improve budgie theming
- [x]  Improve header theming
- [x]  Improve nautilus sidebar
- [x]  Improve popover theming

**Comment by Ste74** [comment]
Do you want to update this theme? Great, I removed from Manjaro why did not support gtk3.20 :wink:

**Comment by ikeydoherty** [comment]
So I'm wondering now that this repo is active again where it should be moved to..

`solus-cold-storage` is for dead/defunct projects, not one's being actively maintained?

**Comment by poltertec** [comment]
wherever you wish, I guess ;)
