### ISSUE TITLE
Dark toolbars in LibreOffice (5.1)

### ISSUE THREAD

**Issue by Tigro** [solus-cold-storage/evopop-gtk-theme#63]
Black toolbars in LibreOffice. I think they should be grey...

![2016-06-16 11-37-05](https://cloud.githubusercontent.com/assets/534335/16110575/1c57cb2a-33b7-11e6-844b-00d57b746cc2.png)

**Comment by poltertec** [comment]
K, a bit different then what i am seeing with 5.0.6 :)
Will look into it.
![schermafdruk van 2016-06-16 10-47-49](https://cloud.githubusercontent.com/assets/8506580/16110864/46e1ec7e-33b0-11e6-8036-913db0070d77.png)

**Comment by Tigro** [comment]
Excellent. Thank you very much.

**Comment by poltertec** [comment]
No problemo :)
